### ISSUE TITLE
I've adapted this demo for Bootstrap4

### ISSUE THREAD

**Issue by slavap** [Axellience/vue-gwt-demo#1]
If you wish you can use it somehow. More features of vue-gwt are covered.
https://github.com/slavap/vue-gwt-bootstrap

**Comment by adrienbaron** [comment]
@slavap Thanks! Can I submit push requests to it? Or just replace the current demo with it (of course with credits to you)?

**Comment by slavap** [comment]
@adrienbaron As you wish, you can use it any way you like.

**Comment by adrienbaron** [comment]
@slavap Ok thanks, I'll keep you updated if I use it 👍
