### ISSUE TITLE
Web Resources Other than html files

### ISSUE THREAD

**Issue by mfreeman-xtivia** [Axellience/vue-gwt-demo#3]
So I've been playing with this one for a while and slowly get my mojo (pun intended) down around how it all works. 

But I stumbed into a hmmmm today and was wondering if you had any thoughts about this one. Given the way this POM is constructed (specifically the resource directory **/*.html override combined with resetting the output directory) it seems will cause all of the *.html template files to land in their right package-specific place under WEB-INF/classes. But doing this this way seems to preclude anyone from actually getting real legitimate resources like web.xml from src/main/webapp to be output into the WAR.

I've tried all sorts of tricks today and it seems i can either have web.xml in the right place in the generated WAR, or the *.html files, but not both.

Any thoughts?

**Comment by adrienbaron** [comment]
Hi!

The reason `.html` are copied to the output like this is for the Annotation processor to find them. The HTML templates are actually not needed at runtime, only at compile time. So if you manage to get the compilation (and annotation processing working) and your web.xml copied without the html files then you'll be good to go.
